spring:
  datasource:
    url: jdbc:postgresql://192.168.0.25:6000/db_event
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "1234"
    hikari:
      maximum-pool-size: 5

  sql:
    init:
      mode: always

  flyway:
    enabled: false
