server:
  port: 8040

spring:
  profiles:
    active: local  # 개발 환경

  application:
    name: service-order

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_order}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:10}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

spring.grpc:
  server:
    port: 9040
  client:
    channels:
      service-store:
        address: static://127.0.0.1:9020  # IPv4 명시 (Windows에서 localhost=::1 방지)
      service-delivery:
        address: static://127.0.0.1:9050  # IPv4 명시 (Windows에서 localhost=::1 방지)

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka/